name: coal_tracking_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.1
  custom_info_window: ^1.0.1
  geolocator: ^8.0.5
  flutter_geocoder: ^0.2.2-nullsafety
  geocoding: ^2.0.4
  flutter_polyline_points: ^2.0.0

  modal_bottom_sheet: ^2.0.1

  uuid: ^3.0.5

  http:
  google_fonts:
  path_provider:
  image:
  image_picker:
  get: ^4.6.5
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  lottie: ^2.6.0
  animated_theme_switcher: ^2.0.9
  url_launcher: ^6.1.14
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/